# Form implementation generated from reading ui file 'registerResident.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class register_Secretary(object):
    def setupUi(self, RegisterSecretary):
        RegisterSecretary.setObjectName("RegisterSecretary")
        RegisterSecretary.resize(1350, 745)
        RegisterSecretary.setMaximumSize(QtCore.QSize(1350, 745))
        RegisterSecretary.setStyleSheet("QLineEdit, QComboBox {\n"
"    border: 2px solid #a0a0a0;\n"
"    border-radius: 8px;         \n"
"    padding: 6px 12px;\n"
"    background-color: white;\n"
"    min-height: 20px;\n"
"    font-size: 12px;\n"
"}\n"
"")
        self.scrollArea = QtWidgets.QScrollArea(parent=RegisterSecretary)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1350, 745))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background-color:#E5E7E9;\n"
"}\n"
"")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, -66, 1251, 1005))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_5.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_5.setMinimumSize(QtCore.QSize(1251, 1005))
        self.scrollAreaWidgetContents_5.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}\n"
"")
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.personalInfromationFrame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.personalInfromationFrame_2.setGeometry(QtCore.QRect(290, 100, 980, 481))
        self.personalInfromationFrame_2.setStyleSheet("QFrame {\n"
"    background-color: #f7fff7;   \n"
"    border-radius: 15px;      \n"
"}\n"
"")
        self.personalInfromationFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.personalInfromationFrame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.personalInfromationFrame_2.setObjectName("personalInfromationFrame_2")
        self.personalInformationIcon_3 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.personalInformationIcon_3.setGeometry(QtCore.QRect(15, 10, 31, 31))
        self.personalInformationIcon_3.setText("")
        self.personalInformationIcon_3.setPixmap(QtGui.QPixmap("Assets/icons/personal information.png"))
        self.personalInformationIcon_3.setScaledContents(True)
        self.personalInformationIcon_3.setObjectName("personalInformationIcon_3")
        self.personalInformationLabel_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.personalInformationLabel_2.setGeometry(QtCore.QRect(50, 15, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.personalInformationLabel_2.setFont(font)
        self.personalInformationLabel_2.setObjectName("personalInformationLabel_2")
        self.firstName_3 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.firstName_3.setGeometry(QtCore.QRect(10, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName_3.setFont(font)
        self.firstName_3.setObjectName("firstName_3")
        self.firstNameInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.firstNameInput_2.setGeometry(QtCore.QRect(130, 70, 240, 36))
        self.firstNameInput_2.setObjectName("firstNameInput_2")
        self.middleNameInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.middleNameInput_2.setGeometry(QtCore.QRect(130, 120, 240, 36))
        self.middleNameInput_2.setObjectName("middleNameInput_2")
        self.middleName_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.middleName_2.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.middleName_2.setFont(font)
        self.middleName_2.setObjectName("middleName_2")
        self.lastName_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.lastName_2.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastName_2.setFont(font)
        self.lastName_2.setObjectName("lastName_2")
        self.lastNameInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.lastNameInput_2.setGeometry(QtCore.QRect(130, 170, 240, 36))
        self.lastNameInput_2.setObjectName("lastNameInput_2")
        self.placeOfBirth_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.placeOfBirth_2.setGeometry(QtCore.QRect(10, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeOfBirth_2.setFont(font)
        self.placeOfBirth_2.setObjectName("placeOfBirth_2")
        self.placeOfBirthInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.placeOfBirthInput_2.setGeometry(QtCore.QRect(130, 220, 240, 36))
        self.placeOfBirthInput_2.setObjectName("placeOfBirthInput_2")
        self.dateOfBirth_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.dateOfBirth_2.setGeometry(QtCore.QRect(10, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateOfBirth_2.setFont(font)
        self.dateOfBirth_2.setObjectName("dateOfBirth_2")
        self.dateOfBirthInput_2 = QtWidgets.QDateEdit(parent=self.personalInfromationFrame_2)
        self.dateOfBirthInput_2.setGeometry(QtCore.QRect(130, 320, 101, 31))
        self.dateOfBirthInput_2.setObjectName("dateOfBirthInput_2")
        self.nationality_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.nationality_2.setGeometry(QtCore.QRect(10, 370, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nationality_2.setFont(font)
        self.nationality_2.setObjectName("nationality_2")
        self.nationalityComboBox_2 = QtWidgets.QComboBox(parent=self.personalInfromationFrame_2)
        self.nationalityComboBox_2.setGeometry(QtCore.QRect(130, 370, 101, 36))
        self.nationalityComboBox_2.setObjectName("nationalityComboBox_2")
        self.nationalityComboBox_2.addItem("")
        self.nationalityComboBox_2.addItem("")
        self.nationalityComboBox_2.addItem("")
        self.nationalityComboBox_2.addItem("")
        self.nationalityComboBox_2.addItem("")
        self.nationalityComboBox_2.addItem("")
        self.nationalityComboBox_2.addItem("")
        self.otherInput_4 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.otherInput_4.setEnabled(False)
        self.otherInput_4.setGeometry(QtCore.QRect(240, 370, 131, 36))
        self.otherInput_4.setClearButtonEnabled(False)
        self.otherInput_4.setObjectName("otherInput_4")
        self.religion_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.religion_2.setGeometry(QtCore.QRect(10, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.religion_2.setFont(font)
        self.religion_2.setObjectName("religion_2")
        self.religionComboBox_2 = QtWidgets.QComboBox(parent=self.personalInfromationFrame_2)
        self.religionComboBox_2.setGeometry(QtCore.QRect(130, 420, 101, 36))
        self.religionComboBox_2.setObjectName("religionComboBox_2")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.religionComboBox_2.addItem("")
        self.otherInput_5 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.otherInput_5.setEnabled(False)
        self.otherInput_5.setGeometry(QtCore.QRect(240, 420, 131, 36))
        self.otherInput_5.setClearButtonEnabled(False)
        self.otherInput_5.setObjectName("otherInput_5")
        self.firstName_4 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.firstName_4.setGeometry(QtCore.QRect(10, 270, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstName_4.setFont(font)
        self.firstName_4.setObjectName("firstName_4")
        self.sexComboBox_2 = QtWidgets.QComboBox(parent=self.personalInfromationFrame_2)
        self.sexComboBox_2.setGeometry(QtCore.QRect(130, 270, 101, 36))
        self.sexComboBox_2.setObjectName("sexComboBox_2")
        self.sexComboBox_2.addItem("")
        self.sexComboBox_2.addItem("")
        self.sexComboBox_2.addItem("")
        self.otherInput_6 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.otherInput_6.setEnabled(False)
        self.otherInput_6.setGeometry(QtCore.QRect(240, 270, 131, 36))
        self.otherInput_6.setClearButtonEnabled(False)
        self.otherInput_6.setObjectName("otherInput_6")
        self.deceased_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.deceased_2.setGeometry(QtCore.QRect(450, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deceased_2.setFont(font)
        self.deceased_2.setObjectName("deceased_2")
        self.deceasedBox_2 = QtWidgets.QCheckBox(parent=self.personalInfromationFrame_2)
        self.deceasedBox_2.setGeometry(QtCore.QRect(541, 120, 21, 31))
        self.deceasedBox_2.setText("")
        self.deceasedBox_2.setObjectName("deceasedBox_2")
        self.pwdCheckBox_2 = QtWidgets.QCheckBox(parent=self.personalInfromationFrame_2)
        self.pwdCheckBox_2.setGeometry(QtCore.QRect(650, 120, 21, 31))
        self.pwdCheckBox_2.setText("")
        self.pwdCheckBox_2.setObjectName("pwdCheckBox_2")
        self.pwd_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.pwd_2.setGeometry(QtCore.QRect(590, 120, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pwd_2.setFont(font)
        self.pwd_2.setObjectName("pwd_2")
        self.bloodType_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.bloodType_2.setGeometry(QtCore.QRect(450, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bloodType_2.setFont(font)
        self.bloodType_2.setObjectName("bloodType_2")
        self.bloodTypeInput_2 = QtWidgets.QComboBox(parent=self.personalInfromationFrame_2)
        self.bloodTypeInput_2.setGeometry(QtCore.QRect(570, 170, 81, 36))
        self.bloodTypeInput_2.setObjectName("bloodTypeInput_2")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.bloodTypeInput_2.addItem("")
        self.heightInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.heightInput_2.setGeometry(QtCore.QRect(570, 220, 81, 36))
        self.heightInput_2.setObjectName("heightInput_2")
        self.height_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.height_2.setGeometry(QtCore.QRect(450, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.height_2.setFont(font)
        self.height_2.setObjectName("height_2")
        self.weight_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.weight_2.setGeometry(QtCore.QRect(450, 270, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weight_2.setFont(font)
        self.weight_2.setObjectName("weight_2")
        self.weightInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.weightInput_2.setGeometry(QtCore.QRect(570, 270, 81, 36))
        self.weightInput_2.setObjectName("weightInput_2")
        self.contactNumberInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.contactNumberInput_2.setGeometry(QtCore.QRect(590, 70, 240, 36))
        self.contactNumberInput_2.setObjectName("contactNumberInput_2")
        self.contactNumber_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.contactNumber_2.setGeometry(QtCore.QRect(450, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactNumber_2.setFont(font)
        self.contactNumber_2.setObjectName("contactNumber_2")
        self.civilStatus_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.civilStatus_2.setGeometry(QtCore.QRect(450, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.civilStatus_2.setFont(font)
        self.civilStatus_2.setObjectName("civilStatus_2")
        self.civilStatusInput_2 = QtWidgets.QComboBox(parent=self.personalInfromationFrame_2)
        self.civilStatusInput_2.setGeometry(QtCore.QRect(570, 320, 101, 36))
        self.civilStatusInput_2.setObjectName("civilStatusInput_2")
        self.civilStatusInput_2.addItem("")
        self.civilStatusInput_2.addItem("")
        self.civilStatusInput_2.addItem("")
        self.civilStatusInput_2.addItem("")
        self.fathersNameInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.fathersNameInput_2.setGeometry(QtCore.QRect(580, 370, 240, 36))
        self.fathersNameInput_2.setObjectName("fathersNameInput_2")
        self.fathersName_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.fathersName_2.setGeometry(QtCore.QRect(450, 370, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fathersName_2.setFont(font)
        self.fathersName_2.setObjectName("fathersName_2")
        self.mothersName_2 = QtWidgets.QLabel(parent=self.personalInfromationFrame_2)
        self.mothersName_2.setGeometry(QtCore.QRect(450, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mothersName_2.setFont(font)
        self.mothersName_2.setObjectName("mothersName_2")
        self.mothersNameInput_2 = QtWidgets.QLineEdit(parent=self.personalInfromationFrame_2)
        self.mothersNameInput_2.setGeometry(QtCore.QRect(580, 420, 240, 36))
        self.mothersNameInput_2.setObjectName("mothersNameInput_2")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.frame.setGeometry(QtCore.QRect(290, 30, 980, 61))
        self.frame.setStyleSheet("""
            QFrame {
                background-color: #f0f7ff; 
                border-radius: 12px;
                border: 1px solid #d0e1f9;
                border-bottom: 3px solid #3498db; 
            }
            QLabel {
                color: #1a2a3a;
                border: none;
                background: transparent;
                font-weight: bold;
            }
        """)

        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.dateTime_Label = QtWidgets.QLabel(parent=self.frame)
        self.dateTime_Label.setGeometry(QtCore.QRect(660, 20, 400, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.dateTime_Label.setFont(font)
        self.dateTime_Label.setObjectName("dateTime_Label")
        self.icon = QtWidgets.QLabel(parent=self.frame)
        self.icon.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("Assets/icons/home (2).png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.registerResident_2 = QtWidgets.QLabel(parent=self.frame)
        self.registerResident_2.setGeometry(QtCore.QRect(60, 20, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.registerResident_2.setFont(font)
        self.registerResident_2.setObjectName("registerResident_2")
        self.contactInformationFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.contactInformationFrame.setGeometry(QtCore.QRect(730, 590, 540, 241))
        self.contactInformationFrame.setStyleSheet("QFrame {\n"
"    background-color: #f7fff7;   \n"
"    border-radius: 15px;      \n"
"}\n"
"")
        self.contactInformationFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.contactInformationFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contactInformationFrame.setObjectName("contactInformationFrame")
        self.contactInformationIcon = QtWidgets.QLabel(parent=self.contactInformationFrame)
        self.contactInformationIcon.setGeometry(QtCore.QRect(15, 10, 31, 31))
        self.contactInformationIcon.setText("")
        self.contactInformationIcon.setPixmap(QtGui.QPixmap("Assets/icons/contact information.png"))
        self.contactInformationIcon.setScaledContents(True)
        self.contactInformationIcon.setWordWrap(False)
        self.contactInformationIcon.setObjectName("contactInformationIcon")
        self.contactInfromationLabel = QtWidgets.QLabel(parent=self.contactInformationFrame)
        self.contactInfromationLabel.setGeometry(QtCore.QRect(50, 15, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.contactInfromationLabel.setFont(font)
        self.contactInfromationLabel.setObjectName("contactInfromationLabel")
        self.email = QtWidgets.QLabel(parent=self.contactInformationFrame)
        self.email.setGeometry(QtCore.QRect(10, 70, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.emailInput = QtWidgets.QLineEdit(parent=self.contactInformationFrame)
        self.emailInput.setGeometry(QtCore.QRect(240, 70, 240, 36))
        self.emailInput.setObjectName("emailInput")
        self.emergencyContactName = QtWidgets.QLabel(parent=self.contactInformationFrame)
        self.emergencyContactName.setGeometry(QtCore.QRect(10, 120, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.emergencyContactName.setFont(font)
        self.emergencyContactName.setObjectName("emergencyContactName")
        self.emergencyContactNameInput = QtWidgets.QLineEdit(parent=self.contactInformationFrame)
        self.emergencyContactNameInput.setGeometry(QtCore.QRect(240, 120, 240, 36))
        self.emergencyContactNameInput.setObjectName("emergencyContactNameInput")
        self.emergencyContactNumberInput = QtWidgets.QLineEdit(parent=self.contactInformationFrame)
        self.emergencyContactNumberInput.setGeometry(QtCore.QRect(240, 170, 240, 36))
        self.emergencyContactNumberInput.setObjectName("emergencyContactNumberInput")
        self.EmergencyContactNumber = QtWidgets.QLabel(parent=self.contactInformationFrame)
        self.EmergencyContactNumber.setGeometry(QtCore.QRect(10, 170, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EmergencyContactNumber.setFont(font)
        self.EmergencyContactNumber.setObjectName("EmergencyContactNumber")
        self.addressInformationFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.addressInformationFrame.setGeometry(QtCore.QRect(290, 590, 430, 241))
        self.addressInformationFrame.setStyleSheet("QFrame {\n"
"    background-color: #f7fff7;   \n"
"    border-radius: 15px;      \n"
"}\n"
"")
        self.addressInformationFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.addressInformationFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.addressInformationFrame.setObjectName("addressInformationFrame")
        self.addressInformationIcon = QtWidgets.QLabel(parent=self.addressInformationFrame)
        self.addressInformationIcon.setGeometry(QtCore.QRect(5, 5, 51, 41))
        self.addressInformationIcon.setText("")
        self.addressInformationIcon.setPixmap(QtGui.QPixmap("Assets/icons/address Information.png"))
        self.addressInformationIcon.setScaledContents(True)
        self.addressInformationIcon.setWordWrap(False)
        self.addressInformationIcon.setObjectName("addressInformationIcon")
        self.addressInfromationLabel = QtWidgets.QLabel(parent=self.addressInformationFrame)
        self.addressInfromationLabel.setGeometry(QtCore.QRect(50, 15, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.addressInfromationLabel.setFont(font)
        self.addressInfromationLabel.setObjectName("addressInfromationLabel")
        self.purokInput = QtWidgets.QComboBox(parent=self.addressInformationFrame)
        self.purokInput.setGeometry(QtCore.QRect(130, 70, 101, 36))
        self.purokInput.setObjectName("purokInput")
        self.purokInput.addItem("")
        self.purokInput.addItem("")
        self.purokInput.addItem("")
        self.purokInput.addItem("")
        self.purokInput.addItem("")
        self.purok = QtWidgets.QLabel(parent=self.addressInformationFrame)
        self.purok.setGeometry(QtCore.QRect(10, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.purok.setFont(font)
        self.purok.setObjectName("purok")
        self.street = QtWidgets.QLabel(parent=self.addressInformationFrame)
        self.street.setGeometry(QtCore.QRect(10, 120, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.street.setFont(font)
        self.street.setObjectName("street")
        self.streetInput = QtWidgets.QLineEdit(parent=self.addressInformationFrame)
        self.streetInput.setGeometry(QtCore.QRect(130, 120, 240, 36))
        self.streetInput.setObjectName("streetInput")
        self.houseID = QtWidgets.QLabel(parent=self.addressInformationFrame)
        self.houseID.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.houseID.setFont(font)
        self.houseID.setObjectName("houseID")
        self.houseIDInput = QtWidgets.QLineEdit(parent=self.addressInformationFrame)
        self.houseIDInput.setGeometry(QtCore.QRect(130, 170, 240, 36))
        self.houseIDInput.setObjectName("houseIDInput")
        self.registerResidentButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_5)
        self.registerResidentButton.setGeometry(QtCore.QRect(1020, 860, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.registerResidentButton.setFont(font)
        self.registerResidentButton.setStyleSheet("QPushButton {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: Segoe UI;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    transition: background-color 0.1s;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #34495e;  \n"
"    padding: 11px 10px 9px 10px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #34495e;\n"
"}")
        self.registerResidentButton.setFlat(False)
        self.registerResidentButton.setObjectName("registerResidentButton")
        self.sidePanel = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_5)
        self.sidePanel.setEnabled(True)
        self.sidePanel.setGeometry(QtCore.QRect(0, 0, 261, 1011))
        self.sidePanel.setStyleSheet("QFrame {\n"
"    border: 2px solid #2C3E50;   \n"
"    border-radius: 10px;         \n"
"    background-color: #2C3E50;   \n"
"}")
        self.sidePanel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidePanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sidePanel.setObjectName("sidePanel")
        self.secretary_Label_2 = QtWidgets.QLabel(parent=self.sidePanel)
        self.secretary_Label_2.setGeometry(QtCore.QRect(80, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.secretary_Label_2.setFont(font)
        self.secretary_Label_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"  
"    border: none;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"}")
        self.secretary_Label_2.setObjectName("secretary_Label_2")
        self.viewPopulation_Button_2 = QtWidgets.QPushButton(parent=self.sidePanel)
        self.viewPopulation_Button_2.setGeometry(QtCore.QRect(89, 340, 125, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewPopulation_Button_2.setFont(font)
        self.viewPopulation_Button_2.setStyleSheet("""
QPushButton {
    background-color: transparent;
    border: none;
    color: #FFFFFF;             
    font-weight: bold;          
    text-align: left;           
    padding-left: 5px;          
}

QPushButton:hover {
    background-color: #34495E;
    border-radius: 5px;
}
""")
        self.viewPopulation_Button_2.setDefault(False)
        self.viewPopulation_Button_2.setFlat(True)
        self.viewPopulation_Button_2.setObjectName("viewPopulation_Button_2")
        self.register_Button_2 = QtWidgets.QPushButton(parent=self.sidePanel)
        self.register_Button_2.setGeometry(QtCore.QRect(87, 380, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.register_Button_2.setFont(font)
        self.register_Button_2.setStyleSheet("""
QPushButton {
    background-color: #467099;
    border: none;
    color: #FFFFFF;             
    font-weight: bold;          
    text-align: left;           
    padding-left: 5px;          
}

QPushButton:hover {
    background-color: #34495E;
    border-radius: 5px;
}
""")
        self.register_Button_2.setFlat(True)
        self.register_Button_2.setObjectName("register_Button_2")
        self.generateReports_Button_2 = QtWidgets.QPushButton(parent=self.sidePanel)
        self.generateReports_Button_2.setGeometry(QtCore.QRect(87, 420, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.generateReports_Button_2.setFont(font)
        self.generateReports_Button_2.setStyleSheet("""
QPushButton {
    background-color: transparent;
    border: none;
    color: #FFFFFF;             
    font-weight: bold;          
    text-align: left;           
    padding-left: 5px;          
}

QPushButton:hover {
    background-color: #34495E;
    border-radius: 5px;
}
""")
        self.generateReports_Button_2.setFlat(True)
        self.generateReports_Button_2.setObjectName("generateReports_Button_2")
        self.logout_Button_3 = QtWidgets.QPushButton(parent=self.sidePanel)
        self.logout_Button_3.setGeometry(QtCore.QRect(48, 860, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logout_Button_3.setFont(font)
        self.logout_Button_3.setStyleSheet(" QPushButton {\n"
"                background-color: #dc3545;\n"
"                color: white;\n"
"                border: none;\n"
"                border-radius: 5px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #c82333;\n"
"            }")
        self.logout_Button_3.setFlat(False)
        self.logout_Button_3.setObjectName("logout_Button_3")
        self.logo_2 = QtWidgets.QLabel(parent=self.sidePanel)
        self.logo_2.setGeometry(QtCore.QRect(42, 50, 191,171))
        self.logo_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("Assets/logo/logo 3.png"))
        self.logo_2.setScaledContents(True)
        self.logo_2.setWordWrap(False)
        self.logo_2.setOpenExternalLinks(False)
        self.logo_2.setObjectName("logo_2")
        self.home_2 = QtWidgets.QLabel(parent=self.sidePanel)
        self.home_2.setGeometry(QtCore.QRect(50, 295, 35, 25))
        self.home_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.home_2.setText("")
        self.home_2.setPixmap(QtGui.QPixmap("Assets/icons/homepage new.png"))
        self.home_2.setScaledContents(True)
        self.home_2.setWordWrap(False)
        self.home_2.setObjectName("home_2")
        self.viewPopulation_2 = QtWidgets.QLabel(parent=self.sidePanel)
        self.viewPopulation_2.setGeometry(QtCore.QRect(45, 335, 40, 25))
        self.viewPopulation_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.viewPopulation_2.setText("")
        self.viewPopulation_2.setPixmap(QtGui.QPixmap("Assets/icons/view population new.png"))
        self.viewPopulation_2.setScaledContents(True)
        self.viewPopulation_2.setWordWrap(False)
        self.viewPopulation_2.setObjectName("viewPopulation_2")
        self.generateReports_2 = QtWidgets.QLabel(parent=self.sidePanel)
        self.generateReports_2.setGeometry(QtCore.QRect(45, 415, 39, 25))
        self.generateReports_2.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.generateReports_2.setText("")
        self.generateReports_2.setPixmap(QtGui.QPixmap("Assets/icons/generate report new.png"))
        self.generateReports_2.setScaledContents(True)
        self.generateReports_2.setWordWrap(False)
        self.generateReports_2.setObjectName("generateReports_2")
        self.home_Button_3 = QtWidgets.QPushButton(parent=self.sidePanel)
        self.home_Button_3.setGeometry(QtCore.QRect(90, 300, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_Button_3.setFont(font)
        self.home_Button_3.setStyleSheet("""
QPushButton {
    background-color: transparent;
    border: none;
    color: #FFFFFF;             
    font-weight: bold;          
    text-align: left;           
    padding-left: 5px;          
}

QPushButton:hover {
    background-color: #34495E;
    border-radius: 5px;
}
""")
        self.home_Button_3.setFlat(False)
        self.home_Button_3.setObjectName("home_Button_3")
        self.registerResident_3 = QtWidgets.QLabel(parent=self.sidePanel)
        self.registerResident_3.setGeometry(QtCore.QRect(45, 375, 39, 25))
        self.registerResident_3.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.registerResident_3.setText("")
        self.registerResident_3.setPixmap(QtGui.QPixmap("Assets/icons/add new.png"))
        self.registerResident_3.setScaledContents(True)
        self.registerResident_3.setWordWrap(False)
        self.registerResident_3.setObjectName("registerResident_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)

        self.retranslateUi(RegisterSecretary)
        QtCore.QMetaObject.connectSlotsByName(RegisterSecretary)

    def retranslateUi(self, RegisterSecretary):
        _translate = QtCore.QCoreApplication.translate
        RegisterSecretary.setWindowTitle(_translate("RegisterSecretary", "Register Resident"))
        self.personalInformationLabel_2.setText(_translate("RegisterSecretary", "PESRONAL INFORMATION"))
        self.firstName_3.setText(_translate("RegisterSecretary", "First Name:"))
        self.middleName_2.setText(_translate("RegisterSecretary", "Middle Name:"))
        self.lastName_2.setText(_translate("RegisterSecretary", "Last Name:"))
        self.placeOfBirth_2.setText(_translate("RegisterSecretary", "Place of Birth:"))
        self.dateOfBirth_2.setText(_translate("RegisterSecretary", "Date of Birth:"))
        self.nationality_2.setText(_translate("RegisterSecretary", "Nationality:"))
        self.nationalityComboBox_2.setItemText(0, _translate("RegisterSecretary", "Filipino"))
        self.nationalityComboBox_2.setItemText(1, _translate("RegisterSecretary", "American"))
        self.nationalityComboBox_2.setItemText(2, _translate("RegisterSecretary", "Chinese"))
        self.nationalityComboBox_2.setItemText(3, _translate("RegisterSecretary", "Korean"))
        self.nationalityComboBox_2.setItemText(4, _translate("RegisterSecretary", "Japanese"))
        self.nationalityComboBox_2.setItemText(5, _translate("RegisterSecretary", "Indian"))
        self.nationalityComboBox_2.setItemText(6, _translate("RegisterSecretary", "Others:"))
        self.otherInput_4.setPlaceholderText(_translate("RegisterSecretary", "Please specify"))
        self.religion_2.setText(_translate("RegisterSecretary", "Religion:"))
        self.religionComboBox_2.setItemText(0, _translate("RegisterSecretary", "Roman Catholic"))
        self.religionComboBox_2.setItemText(1, _translate("RegisterSecretary", "Inglesia ni Cristo"))
        self.religionComboBox_2.setItemText(2, _translate("RegisterSecretary", "Born Again"))
        self.religionComboBox_2.setItemText(3, _translate("RegisterSecretary", "Muslim"))
        self.religionComboBox_2.setItemText(4, _translate("RegisterSecretary", "Buddhism"))
        self.religionComboBox_2.setItemText(5, _translate("RegisterSecretary", "Hinduism"))
        self.religionComboBox_2.setItemText(6, _translate("RegisterSecretary", "None"))
        self.religionComboBox_2.setItemText(7, _translate("RegisterSecretary", "Other:"))
        self.otherInput_5.setPlaceholderText(_translate("RegisterSecretary", "Please specify"))
        self.firstName_4.setText(_translate("RegisterSecretary", "Sex:"))
        self.sexComboBox_2.setItemText(0, _translate("RegisterSecretary", "Male"))
        self.sexComboBox_2.setItemText(1, _translate("RegisterSecretary", "Female"))
        self.sexComboBox_2.setItemText(2, _translate("RegisterSecretary", "Other:"))
        self.otherInput_6.setPlaceholderText(_translate("RegisterSecretary", "Please specify"))
        self.deceased_2.setText(_translate("RegisterSecretary", "Deceased:"))
        self.pwd_2.setText(_translate("RegisterSecretary", "PWD:"))
        self.bloodType_2.setText(_translate("RegisterSecretary", "Blood Type:"))
        self.bloodTypeInput_2.setItemText(0, _translate("RegisterSecretary", "A+"))
        self.bloodTypeInput_2.setItemText(1, _translate("RegisterSecretary", "A-"))
        self.bloodTypeInput_2.setItemText(2, _translate("RegisterSecretary", "B+"))
        self.bloodTypeInput_2.setItemText(3, _translate("RegisterSecretary", "B-"))
        self.bloodTypeInput_2.setItemText(4, _translate("RegisterSecretary", "AB+"))
        self.bloodTypeInput_2.setItemText(5, _translate("RegisterSecretary", "AB-"))
        self.bloodTypeInput_2.setItemText(6, _translate("RegisterSecretary", "O+"))
        self.bloodTypeInput_2.setItemText(7, _translate("RegisterSecretary", "O-"))
        self.heightInput_2.setPlaceholderText(_translate("RegisterSecretary", "cm"))
        self.height_2.setText(_translate("RegisterSecretary", "Height(cm):"))
        self.weight_2.setText(_translate("RegisterSecretary", "Weight(kg):"))
        self.weightInput_2.setPlaceholderText(_translate("RegisterSecretary", "kg"))
        self.contactNumber_2.setText(_translate("RegisterSecretary", "Contact Number:"))
        self.civilStatus_2.setText(_translate("RegisterSecretary", "Civil Status:"))
        self.civilStatusInput_2.setItemText(0, _translate("RegisterSecretary", "Single"))
        self.civilStatusInput_2.setItemText(1, _translate("RegisterSecretary", "Married"))
        self.civilStatusInput_2.setItemText(2, _translate("RegisterSecretary", "Widowed"))
        self.civilStatusInput_2.setItemText(3, _translate("RegisterSecretary", "Separated"))
        self.fathersName_2.setText(_translate("RegisterSecretary", "Father\'s Name:"))
        self.mothersName_2.setText(_translate("RegisterSecretary", "Mother\'s Name:"))
        self.dateTime_Label.setText(_translate("RegisterSecretary", "date and time"))
        self.registerResident_2.setText(_translate("RegisterSecretary", "REGISTER RESIDENT"))
        self.contactInfromationLabel.setText(_translate("RegisterSecretary", "CONTACT INFORMATION"))
        self.email.setText(_translate("RegisterSecretary", "Email:"))
        self.emergencyContactName.setText(_translate("RegisterSecretary", "Emergency Contact Name:"))
        self.EmergencyContactNumber.setText(_translate("RegisterSecretary", "Emergency Contact Number:"))
        self.addressInfromationLabel.setText(_translate("RegisterSecretary", "ADDRESS INFORMATION"))
        self.purokInput.setItemText(0, _translate("RegisterSecretary", "Purok 1"))
        self.purokInput.setItemText(1, _translate("RegisterSecretary", "Purok 2"))
        self.purokInput.setItemText(2, _translate("RegisterSecretary", "Purok 3"))
        self.purokInput.setItemText(3, _translate("RegisterSecretary", "Purok 4"))
        self.purokInput.setItemText(4, _translate("RegisterSecretary", "Purok 5"))
        self.purok.setText(_translate("RegisterSecretary", "Purok:"))
        self.street.setText(_translate("RegisterSecretary", "Street:"))
        self.houseID.setText(_translate("RegisterSecretary", "House ID:"))
        self.registerResidentButton.setText(_translate("RegisterSecretary", "REGISTER RESIDENT"))
        self.secretary_Label_2.setText(_translate("RegisterSecretary", "SECRETARY"))
        self.viewPopulation_Button_2.setText(_translate("RegisterSecretary", "VIEW POPULATION"))
        self.register_Button_2.setText(_translate("RegisterSecretary", "REGISTER RESIDENT"))
        self.generateReports_Button_2.setText(_translate("RegisterSecretary", "GENERATE REPORTS"))
        self.logout_Button_3.setText(_translate("RegisterSecretary", "LOGOUT"))
        self.home_Button_3.setText(_translate("RegisterSecretary", "DASHBOARD"))
