# Form implementation generated from reading ui file 'loginPage_Secretary.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class loginPage_Secretary(object):
    def setupUi(self, loginPage_QDialog):
        self.loginPage = loginPage_QDialog
        loginPage_QDialog.setObjectName("loginPage_QDialog")
        loginPage_QDialog.resize(771, 474)
        loginPage_QDialog.setWindowTitle("Python")
        loginPage_QDialog.setStyleSheet("QDialog {\n"
"    background-color: \n"
"#81cdeb\n"
"}\n"
"")
        # frame and widgets setup
        self.login_QFrame = QtWidgets.QFrame(parent=loginPage_QDialog)
        self.login_QFrame.setGeometry(QtCore.QRect(330, 40, 401, 391))
        self.login_QFrame.setStyleSheet("QDialog {\n"
"    background-color: transparent; \n"
"}\n"
"QFrame {\n"
"    background-color: white;\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.login_QFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_QFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_QFrame.setObjectName("login_QFrame")

        # Labels, LineEdits, Buttons
        self.header_QLabel = QtWidgets.QLabel(parent=self.login_QFrame)
        self.header_QLabel.setGeometry(QtCore.QRect(180, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.header_QLabel.setFont(font)
        self.header_QLabel.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"font-family: Segoe UI;\n"
"font-size: 26px;\n"
"font-weight: bold;")
        self.header_QLabel.setObjectName("header_QLabel")
        self.username_QLabel = QtWidgets.QLabel(parent=self.login_QFrame)
        self.username_QLabel.setGeometry(QtCore.QRect(20, 130, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.username_QLabel.setFont(font)
        self.username_QLabel.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"font-family: Segoe UI;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.username_QLabel.setObjectName("username_QLabel")
        self.password_QLabel = QtWidgets.QLabel(parent=self.login_QFrame)
        self.password_QLabel.setGeometry(QtCore.QRect(20, 210, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.password_QLabel.setFont(font)
        self.password_QLabel.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"font-family: Segoe UI;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.password_QLabel.setObjectName("password_QLabel")

        # Username & Password
        self.username_QLineEdit = QtWidgets.QLineEdit(parent=self.login_QFrame)
        self.username_QLineEdit.setGeometry(QtCore.QRect(20, 160, 361, 31))
        self.username_QLineEdit.setStyleSheet("background-color: white;\n"
"border: 1px solid #d0d0d0;\n"
"border-radius: 8px;\n"
"padding: 8px;\n"
"font-family: Segoe UI;\n"
"font-size: 14px;")
        self.username_QLineEdit.setObjectName("username_QLineEdit")
        self.password_QLineEdit = QtWidgets.QLineEdit(parent=self.login_QFrame)
        self.password_QLineEdit.setGeometry(QtCore.QRect(20, 240, 361, 31))
        self.password_QLineEdit.setStyleSheet("background-color: white;\n"
"border: 1px solid #d0d0d0;\n"
"border-radius: 8px;\n"
"padding: 8px;\n"
"font-family: Segoe UI;\n"
"font-size: 14px;")

        self.showPasswordButton = QtWidgets.QPushButton(parent=self.password_QLineEdit)
        self.showPasswordButton.setGeometry(QtCore.QRect(330, 5, 24, 24))
        self.showPasswordButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.showPasswordButton.setStyleSheet("border: none; background: transparent;")
        self.showPasswordButton.setIcon(QtGui.QIcon("Assets/icons/openEye.png"))
        self.showPasswordButton.setCheckable(True)
        self.showPasswordButton.clicked.connect(self.togglePassword)

        self.password_QLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.password_QLineEdit.setObjectName("password_QLineEdit")
        self.information_QLabel = QtWidgets.QLabel(parent=self.login_QFrame)
        self.information_QLabel.setGeometry(QtCore.QRect(115, 80, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        self.information_QLabel.setFont(font)
        self.information_QLabel.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"font-family: Segoe UI;\n"
"font-size: 13px;\n"
"font-weight: bold;")
        self.information_QLabel.setObjectName("information_QLabel")
        self.submitButton_QPushButton = QtWidgets.QPushButton(parent=self.login_QFrame)
        self.submitButton_QPushButton.setGeometry(QtCore.QRect(20, 300, 361, 41))
        self.submitButton_QPushButton.setStyleSheet("background-color: #2c3e50;\n"
"color: white;\n"
"border: none;\n"
"border-radius: 8px;\n"
"padding: 10px;\n"
"font-family: Segoe UI;\n"
"font-size: 14px;\n"
"font-weight: bold;")
        self.submitButton_QPushButton.setObjectName("submitButton_QPushButton")

        # Logo
        self.label = QtWidgets.QLabel(parent=loginPage_QDialog)
        self.label.setGeometry(QtCore.QRect(20, 100, 281, 241))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Assets/logo/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(loginPage_QDialog)
        QtCore.QMetaObject.connectSlotsByName(loginPage_QDialog)

    def retranslateUi(self, loginPage_QDialog):
        _translate = QtCore.QCoreApplication.translate
        self.header_QLabel.setText(_translate("loginPage_QDialog", "BPS"))
        self.username_QLabel.setText(_translate("loginPage_QDialog", "USERNAME:"))
        self.password_QLabel.setText(_translate("loginPage_QDialog", "PASSWORD:"))
        self.information_QLabel.setText(_translate("loginPage_QDialog", " Enter Your Login Credentials"))
        self.submitButton_QPushButton.setText(_translate("loginPage_QDialog", "SUBMIT"))

    def togglePassword(self):
        if self.showPasswordButton.isChecked():
            self.password_QLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
            self.showPasswordButton.setIcon(QtGui.QIcon("Assets/icons/closeEye.png"))
        else:
            self.password_QLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
            self.showPasswordButton.setIcon(QtGui.QIcon("Assets/icons/openEye.png"))
